# Generated by Django 2.1.3 on 2018-11-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='photography/photos')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['likes', '-taken_time'],
            },
        ),
    ]
