# Generated by Django 2.1.3 on 2018-11-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['likes']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='taken_time',
        ),
    ]
