# Generated by Django 2.1.3 on 2018-11-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20181114_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-likes']},
        ),
    ]
