# Generated by Django 2.1.3 on 2018-11-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-pub_date']},
        ),
    ]
